name: Run Java Application

on:
  workflow_dispatch:
    inputs:
      stringA:
        description: 'Первая строка'
        required: true
        default: 'hello'
      stringB:
        description: 'Вторая строка'
        required: true
        default: 'world'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile
        run: javac src/ComparisonString.java

      - name: Run
        run: |
          printf "${{ github.event.inputs.stringA }}\n${{ github.event.inputs.stringB }}\n" | java -cp src ComparisonString